const sentences = [
  "Tim Walz fixed your bicycle.",
  "Tim Walz sends birthday texts to everyone he’s ever served with.",
  "Tim Walz clipped you a coupon for that thing you’ve been wanting.",
  "Tim Walz knew exactly when your printer was going to run out of ink.",
  "Tim Walz has a spare one of those out in the shed.",
  "Tim Walz spends saturday mornings at the laundromat with a bag of quarters just in case you’re short.",
  "Tim Walz understands the Infield Fly Rule.",
  "Tim Walz has some jumper cables, just give him a minute.",
  "Tim Walz just shoveled your walk.",
  "Tim Walz made you a plate and none of the food was touching.",
  "Tim Walz hands out full-sized candy bars on Halloween.",
  "Tim Walz hugged you when you came out and said “I love you so much.”",
  "Tim Walz thinks you’re doing a fine job.",
  "Tim Walz is over here if you ever need a hand.",
  "Tim Walz will drive you and your friends to the bead store.",
  "Tim Walz is always ready to pick you up early from your sleepover.",
  "Tim Walz won you a toy from the claw machine.",
  "Tim Walz brought enough for everybody.",
  "Tim Walz isn’t afraid to ask the clerk which aisle the tampons are on.",
  "Tim Walz brought some hotdish.",
  "Tim Walz has an extra Springsteen ticket, if you’re interested.",
  "Tim Walz already has the grill fired up.",
  "Tim Walz brought ice.",
  "Tim Walz is happy to break down the cardboard.",
  "Tim Walz will lend you his drill. No rush to get it back.",
  "Tim Walz doesn’t mind rewatching that show you really want to see.",
  "Tim Walz doesn’t mind rewatching that movie you really want to see.",
  "Tim Walz doesn’t care if it’s less or fewer, he knows what you mean.",
  "Tim Walz will teach you how to parallel park.",
  "Tim Walz sends you New Yorker cartoons you might like and doesn’t mind if you don’t reply.",
  "Tim Walz will go record shopping with you.",
  "Tim Walz says hello to everyone in the post office.",
  "Tim Walz gets the couch joke.",
  "Tim Walz will keep an eye on your kids when you’re running late for school pickup.",
  "Tim Walz will give you back your stapler.",
  "Tim Walz is happy to check over that job application for you.",
  "Tim Walz knows that you should just buy that one Brother printer.",
  "Tim Walz will let you borrow his glasses so you can read the menu.",
  "Tim Walz is glad to give you a hand with your stroller down those stairs.",
  "Tim Walz will give your phone a call when you can’t find yours.",
  "Tim Walz will let you have the window seat.",
  "Tim Walz saw $20 on the ground and left it there.",
  "Tim Walz always texts you back.",
  "Tim Walz loves that you show love, and will spend hours talking with you about it.",
  "Tim Walz would never leave you on read.",
  "Tim Walz will go to your drag show, sit in the front row, and cheer you on.",
  "Tim Walz wants to buy ten tickets for your raffle.",
  "Tim Walz has a scrap of maple from another project that you can use to fix that wobbly shelf.",
  "Tim Walz wants to know if he can pet your dog.",
  "Tim Walz noticed that your rear driver’s side tire is a little low.",
  "Tim Walz carries a spare ice scraper “for situations like this.”",
  "Tim Walz won’t tell your boss you’re unionizing.",
  "Tim Walz always rings your doorbell when he gets to your house.",
  "Tim Walz knows what Minnesota nice is, and he’s not afraid to use it.",
  "Tim Walz remembers where you parked your car.",
  "Tim Walz asks anyone taller than him “How’s the weather up there?”",
  "Tim Walz Venmo’d you for pizza even though he only had a slice.",
  "Tim Walz just shot you finger guns and a smile.",
  "Tim Walz says “right tighty, lefty loosey” every time.",
  "Tim Walz knows how to properly strap down lumber in the back of an old truck.",
  "Tim Walz will point a stud finder at himself and say “Looks like it works.” Every. Single. Time.",
  "Tim Walz is gonna take you and your friends to the Olive Garden. His treat.",
  "Tim Walz will cover your shift so you don’t have to miss the party.",
  "Tim Walz always returns it with a full tank of gas.",
  "Tim Walz only needs one trip to the hardware store.",
  "Tim Walz measures twice. Cuts once.",
  "Tim Walz remembers how you like your steak.",
  "Tim Walz is kind, rewinds.",
  "Tim Walz remembers your kids’ birthdays.",
  "Tim Walz slipped gas money in your pocket without you noticing.",
  "Tim Walz has some advice on how to pack down the minivan for your road trip, if you wanna hear it.",
  "Tim Walz topped off your wiper fluid before you hit the road.",
  "Tim Walz can explain the 3-4 defense and knows when to blitz.",
  "Tim Walz will say “Nice to meet you, hungry,” if he hears you say “I’m hungry.”",
  "Tim Walz can give you a ride to the airport.",
  "Tim Walz doesn’t get a haircut. He gets ALL OF THEM cut.",
  "Tim Walz pulls the car around when it’s raining.",
  "Tim Walz is wondering if you need a hand with that.",
  "Tim Walz keeps a couple cans of your favorite soda in his fridge.",
  "Tim Walz noticed your sink was draining a little slow and took care of it.",
  "Tim Walz fixed your flat.",
  "Tim Walz always has room for a little slice of pie.",
  "Tim Walz remembers whether you like pumpkin or pecan.",
  "Tim Walz invites you around to his friendsgiving.",
  "Tim Walz would be happy to show you how to tie a tie.",
  "Tim Walz left you a note saying he’s looking after that delivery you were waiting for.",
  "Tim Walz watered your plants.",
  "Tim Walz can help you mount your new TV, if you need a hand.",
  "Tim Walz is fine with either pronunciation of pecan, and yes he would love a slice. Please and thank you.",
  "Tim Walz will have what she’s having.",
  "Tim Walz doesn’t mind if you like mayo on your hot dog.",
  "Tim Walz says what bathroom you use is none of his damn business.",
  "Tim Walz doesn’t mind waiting up. He’ll come get you when you need him to.",
  "Tim Walz left you some, it’s in the fridge.",
  "Tim Walz bought those plums and put them in your icebox.",
  "Tim Walz knows that “Die Hard” is a Christmas movie.",
  "Tim Walz would’ve listened to Ripley.",
  "Tim Walz knows when to leave well enough alone.",
  "Tim Walz will help you tidy up afterwards.",
  "Tim Walz will leave the party well before anyone has to ask.",
  "Tim Walz shows up early to help you set up.",
  "Tim Walz sees you struggling with that tent and can definitely hold that in place just for a sec.",
  "Tim Walz will be your dad at graduation, if you want.",
  "Tim Walz knows where you hide the cookies, but would never dream of taking one.",
  "Tim Walz can teach you how to drive stick.",
  "Tim Walz will drive you to your doctor’s appointment if you’re scared of going alone.",
  "Tim Walz isn’t upset with you, he knows everyone makes mistakes.",
  "Tim Walz doesn’t care what color your text bubbles are.",
  "Tim Walz knows you’re doing your best.",
  "Tim Walz cries at the end of “It’s a Wonderful Life.”",
  "Tim Walz has an elegant solution for your technical debt.",
  "Tim Walz holds the door. Even if you are a little too far away.",
  "Tim Walz will never have “more of a comment than a question, really.”",
  "Tim Walz isn’t going to finish his fries. Go ahead and have some.",
  "Tim Walz reported that reply guy for you.",
  "Tim Walz doesn’t read the comments. Doesn’t need to.",
  "Tim Walz knows that wasn’t as easy as you made it look.",
  "Tim Walz knows you tried your best and he’s proud of you.",
  "Tim Walz doesn’t mind if you beat him at Wordle.",
  "Tim Walz knows all the prices on “The Price Is Right.”",
  "Tim Walz wants you to put down the phone and hold the other end of the tape measure.",
  "Tim Walz knows Monopoly isn’t a great board game but will definitely play it with you.",
  "Tim Walz knows how to steer into the skid.",
  "Tim Walz got that reference you made.",
  "Tim Walz will take you back-to-school shopping.",
  "Tim Walz doesn’t care if you jump into the pile of leaves he just raked.",
  "Tim Walz doesn’t mind being corrected, he loves to learn new things.",
  "Tim Walz is happy to lend a hand.",
  "Tim Walz can definitely go with to pick up that Craigslist thing you just bought.",
  "Tim Walz can fax that thing for you.",
  "Tim Walz will count your stitches and won’t say anything when you drop one.",
  "Tim Walz wishes you weren’t still on Facebook, but he gets it.",
  "Tim Walz calls his Sweetwater sales rep to check in on him.",
  "Tim Walz just came over to mow your lawn because he knows you’ve been feeling poorly lately.",
  "Tim Walz says he’s happy to keep an eye on the grill while you get the sides ready.",
  "Tim Walz said your chili was the some of the best he's ever had even though you know you added too much salt.",
  "Tim Walz is the fantasy football commissioner every year. He keeps the trash talk from getting TOO rough.",
  "Tim Walz is happy to learn your pronouns.",
  "Tim Walz says, “You just can’t predict the weather. Why don't you take a sweater with you? Just in case.”",
  "Tim Walz thinks you look amazing just as you are.",
  "Tim Walz ordered fries for the table.",
  "Tim Walz lifts with his legs, not his back.",
  "Tim Walz mutes himself on Zoom when he’s not talking.",
  "Tim Walz keeps an extra toboggan in his Scout.",
  "Tim Walz remembers how you like your coffee.",
  "Tim Walz noticed your new haircut.",
  "Tim Walz says “It’s okay to feel hope.”",
  "Tim Walz would be honored to take a spare key and check in on your place while you’re away.",
  "Tim Walz would go get a mani-pedi with you.",
  "Tim Walz will return the cup of sugar he borrowed.",
  "Tim Walz tips extra, ’cause he knows you’re working hard.",
  "Tim Walz knows the right way to hang a roll of toilet paper.",
  "Tim Walz knows where to rent a tractor, and can help with that stump.",
  "Tim Walz will definitely let you have a turn on his ride-on mower.",
  "Tim Walz believes you.",
  "Tim Walz knows that even Tim Walz is just doing his best.",
  "Tim Walz will let (almost) anybody crash on his couch.",
  "Tim Walz would like to remind you to hydrate.",
  "Tim Walz can show you how to tighten that nut properly.",
  "Tim Walz knows he’s campaigning for us, not him.",
  "Tim Walz waited in line with you to get a Wii.",
  "Tim Walz is no doubt embarrassed and humbled by this website.",
  "Tim Walz is very excited about the Nintendo 64 you got.",
  "Tim Walz will hold your place in line while you run back to pick up tampons.",
  "Tim Walz knows his way around a state fair.",
  "Tim Walz loves when people are excited about their lightsaber technique.",
  "Tim Walz pinned your mittens to your sleeve.",
  "Tim Walz sings “Born to Run” while doing the laundry.",
  "Tim Walz is glad to watch Netflix, fold, and put away laundry with you.",
  "Tim Walz knows which laundry belongs to which person in his family.",
  "Tim Walz does his own research first before asking.",
  "Tim Walz cleaned your gutters for you.",
  "Tim Walz is fine with it if your socks don’t match.",
  "Tim Walz checked the weather and hands you an umbrella as you walk out the door.",
  "Tim Walz will come over if you need help uncluttering. No judgment. He knows how it gets.",
  "Tim Walz uses humane rat traps.",
  "Tim Walz knows which wrench you need and will lend it to you right then and there.",
  "Tim Walz has a spare mask you can have.",
  "Tim Walz is there for you when it’s time for your pet to go.",
  "Tim Walz cheered during the Mona Lisa Vito testimony.",
  "Tim Walz knows it’s complicated. He’s just here to listen.",
  "Tim Walz will happily sit next to you in silence.",
  "Tim Walz ran to catch the ice cream truck for you.",
  "Tim Walz lends you his car while yours is in the shop.",
  "Tim Walz picked up your mail while you were on vacation.",
  "Tim Walz knows when to leave things well enough alone.",
  "Tim Walz carried the diaper bag without being asked.",
  "Tim Walz will put you on his shoulders so you can see the firetrucks.",
  "Tim Walz appreciates the value of a post-dentist lollipop.",
  "Tim Walz has a reserve of extra, pre-sharpened number two pencils.",
  "Tim Walz would never call dibs on a parking spot in February, even though he did spend two hours shoveling it out.",
  "Tim Walz brought homemade cookies, even after being told “No, just bring yourself.”",
  "Tim Walz knows Han shot first.",
  "Tim Walz can help you get that carry-on down from the overhead bin.",
  "Tim Walz insists that you go before him in the checkout line. You’ve only got a couple items.",
  "Tim Walz just wants you to text when you get there.",
  "Tim Walz is happy to see you here and wonders how your family is doing.",
  "Tim Walz will hold your place in line.",
  "Tim Walz takes the pretty way home.",
  "Tim Walz says “We really needed this.” when it rains.",
  "Tim Walz knows they’re not your preferred pronouns, they’re *your* pronouns.",
  "Tim Walz does the edges of the jigsaw puzzle first, and lets you put in the last piece.",
  "Tim Walz will find and fill out that form on LEGO’s website to get that missing piece.",
  "Tim Walz will take the training wheels off your bike.",
  "Tim Walz saved that one email and will re-forward it to you.",
  "Tim Walz returned your Tupperware with some fresh cookies inside.",
  "Tim Walz made sure there were enough hot dog buns at the cookout.",
  "Tim Walz just wants everyone to have joy.",
  "Tim Walz ends phone calls with, “Good to hear your voice!”",
  "Tim Walz says “Ope! Excuse me!” when he accidentally bumps someone.",
  "Tim Walz is proud of that repair you did all by yourself.",
  "Tim Walz can show you how to tie a fish hook, if you’d like to know an easier way.",
  "Tim Walz wrote a LinkedIn Recommendation that made you tear up.",
  "Tim Walz doesn’t brag about donations, he just makes them. They’re no one’s business.",
  "Tim Walz knows how to fold a map.",
  "Tim Walz has never needed GPS in his life.",
  "Tim Walz is undefeated in Soulcalibur.",
  "Tim Walz would never call the salad that you brought to the potluck dessert.",
  "Tim Walz stopped by just to chit-chat when you got stuck doing graveyard watch.",
  "Tim Walz brought orange slices.",
  "Tim Walz prints out articles from the internet to mail to you later.",
  "Tim Walz will patiently explain to your relatives that schools don’t have litter boxes for kids.",
  "Tim Walz was going that way anyway. Hop in.",
  "Tim Walz would love to hear about your Neocities fansite.",
  "Tim Walz keeps both types of phone charger in his car.",
  "Tim Walz saw you sneak an extra scoop of ice cream, but won’t tell. He knows we all need that sometimes.",
  "Tim Walz thinks your baseball card collection looks great.",
  "Tim Walz doesn’t believe in guilty pleasures. Enjoy your silly show.",
  "Tim Walz puts the recipe at the top of the post.",
  "Tim Walz always checks for bike riders before he opens the car door.",
  "Tim Walz doesn’t park in the bike lane.",
  "Tim Walz never met a pool that didn’t get his famous cannonball.",
  "Tim Walz can start a lawnmower every time.",
];

module.exports = sentences;